<!DOCTYPE html>
<html lang="ru">
<head>
    <title>404</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
</head>
<body>
<div id="page-wrap">
    <div id="top_logo_wrap">
        <div class="logo">
        </div>
    </div>
    <div id="page-content">
        <div id="not-found" style="text-align: center; margin: 50px 25px; 100px">
            <h1>404</h1>

            <h2>Page Not Found</h2>

            <p>Visit <a href="/">home page</a></p>
        </div>
    </div>
</div>
</body>
</html>