<!-- Modal -->
<div id="deleteModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Do you really want to delete this entry?</h4>
            </div>
            <div class="modal-body">
                <p>After performing, this actions can't be reverted.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Back</button>
                <a href="#" type="button" class="btn btn-danger delete-action">Remove</a>
            </div>
        </div>

    </div>
</div>
<script type="text/javascript">
    $(function() {
        $('.delete-button').click(function(){
            var deleteUrl = $(this).data().url;
            $('#deleteModal .delete-action').attr('href', deleteUrl);
            $('#deleteModal').modal();
        });
    });
</script>