<!DOCTYPE HTML>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <?php echo $this->headLink()->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>
</head>
<body>
<?php
$msg = 'Application error.';
/** @var \Zend\Http\PhpEnvironment\Response $response */
$response = $this->getHelperPluginManager()->getServiceLocator()->get('response');
if ($response instanceof \Zend\Http\PhpEnvironment\Response) {
    if ($response->getStatusCode() == 401) {
        $msg = 'Access Denied';
    }
}
?>
<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Error</div>
                    <div class="panel-body"><?php echo $msg ?></div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>